version: '2'
services:
    client:
        build:
            context: ./client
            args:
                app_env: ${APP_ENV}
        volumes:
            - ./client/src:/client/src 
        ports:
            - "3000:3000"
    api:
        build: .
        command: ./goproject
        volumes:
            - .:/api
        environment:
            PORT: 8080
        ports:
            - "5000:8080"